// ===========================================================================
// 자동 생성 파일 — 직접 고치지 마세요. 다음 변환 때 덮어써집니다.
// 원본: card_recipe_table_v3.xlsx  (시트: 카드, 레시피)
// 다시 만들기: update-data.bat 더블클릭
//
// 평범한 <script src="cards-data.js"> 로 불러오므로 서버 없이 file:// 에서도
// 동작한다 (fetch 도 module 도 쓰지 않음).
// ===========================================================================

var DATA_GENERATED_AT = "2026-08-25 09:18";

// 변환 중 발견한 데이터 문제. 비어 있지 않으면 게임 화면 위에 배너로 뜬다.
var DATA_WARNINGS = [];

var CARD_DATA = [
  { id: "steel_field", name: "강철 자원지", type: "resourceSite", costResource: "gold", costResourceName: "황금", costAmount: 3, appearsInStartShop: false, appearsInLaterPool: true, startsOnBoard: true, startBoardCount: 1, baseProductionResource: "steel", baseProductionAmount: 1, attack: null, health: null, specialAbility: "", description: "매 턴 시작 시 강철을 1개 생산합니다. 게임 시작 시 보드에 1장 놓여 있습니다." },
  { id: "steel", name: "강철", type: "resource", costResource: null, costResourceName: "", costAmount: null, appearsInStartShop: false, appearsInLaterPool: false, startsOnBoard: false, startBoardCount: null, baseProductionResource: "", baseProductionAmount: null, attack: null, health: null, specialAbility: "", description: "자원지나 건물의 생산물로만 얻는 원자재 카드입니다. 상점에서 직접 구매할 수 없습니다." },
  { id: "oil_field", name: "석유 자원지", type: "resourceSite", costResource: "gold", costResourceName: "황금", costAmount: 3, appearsInStartShop: true, appearsInLaterPool: false, startsOnBoard: false, startBoardCount: 0, baseProductionResource: "oil", baseProductionAmount: 1, attack: null, health: null, specialAbility: "", description: "매 턴 시작 시 석유를 1개 생산합니다." },
  { id: "oil", name: "석유", type: "resource", costResource: null, costResourceName: "", costAmount: null, appearsInStartShop: false, appearsInLaterPool: false, startsOnBoard: false, startBoardCount: null, baseProductionResource: "", baseProductionAmount: null, attack: null, health: null, specialAbility: "", description: "생산으로만 얻는 원자재 카드입니다. 현재는 이 자원을 소모하는 레시피가 없는 비축용 자원입니다." },
  { id: "food_field", name: "식량 자원지", type: "resourceSite", costResource: "gold", costResourceName: "황금", costAmount: 3, appearsInStartShop: false, appearsInLaterPool: true, startsOnBoard: true, startBoardCount: 1, baseProductionResource: "food", baseProductionAmount: 1, attack: null, health: null, specialAbility: "", description: "매 턴 시작 시 식량을 1개 생산합니다. 게임 시작 시 보드에 1장 놓여 있습니다." },
  { id: "food", name: "식량", type: "resource", costResource: null, costResourceName: "", costAmount: null, appearsInStartShop: false, appearsInLaterPool: false, startsOnBoard: false, startBoardCount: null, baseProductionResource: "", baseProductionAmount: null, attack: null, health: null, specialAbility: "", description: "인구 카드를 구매하는 데 사용되는 카드 자원입니다." },
  { id: "white_house", name: "백악관", type: "building/resourceSite", costResource: null, costResourceName: "", costAmount: null, appearsInStartShop: false, appearsInLaterPool: false, startsOnBoard: true, startBoardCount: 1, baseProductionResource: "gold", baseProductionAmount: 1, attack: null, health: null, specialAbility: "", description: "매 턴 시작 시 황금 1을 자동 생산합니다. 지지도 3을 모아 턴 종료 시 소모하면 황금 생산량이 영구히 1 증가합니다(레시피 r01). 상점에서 구매할 수 없는 유일 카드입니다." },
  { id: "support", name: "지지도", type: "resource", costResource: null, costResourceName: "", costAmount: null, appearsInStartShop: false, appearsInLaterPool: false, startsOnBoard: false, startBoardCount: null, baseProductionResource: "", baseProductionAmount: null, attack: null, health: null, specialAbility: "", description: "레시피를 통해서만 얻는 자원 카드입니다." },
  { id: "gold", name: "황금", type: "resource", costResource: null, costResourceName: "", costAmount: null, appearsInStartShop: false, appearsInLaterPool: false, startsOnBoard: false, startBoardCount: null, baseProductionResource: "", baseProductionAmount: null, attack: null, health: null, specialAbility: "", description: "인구를 제외한 모든 카드 구매에 쓰이는 화폐이자 자원 카드입니다. 백악관이 매 턴 생산합니다." },
  { id: "gun_factory", name: "총기 공장", type: "building", costResource: "gold", costResourceName: "황금", costAmount: 2, appearsInStartShop: true, appearsInLaterPool: false, startsOnBoard: false, startBoardCount: 0, baseProductionResource: "", baseProductionAmount: null, attack: null, health: null, specialAbility: "", description: "인구를 올리면 매 턴 총기를 생산합니다. 강철을 함께 올리면 더 많이 생산하고, 총기 설계도를 올리면 추가로 총기를 생산합니다(레시피 r03~r05)." },
  { id: "population", name: "인구", type: "resource", costResource: "food", costResourceName: "식량", costAmount: 3, appearsInStartShop: false, appearsInLaterPool: false, startsOnBoard: false, startBoardCount: 0, baseProductionResource: "", baseProductionAmount: null, attack: null, health: null, specialAbility: "", description: "상점 6번째 고정 슬롯에서 언제든 구매 가능하고, 구매해도 상점에서 사라지지 않습니다. 건물 카드 위에 올려 활성화하는 용도로 쓰입니다." },
  { id: "guns", name: "총기", type: "item", costResource: null, costResourceName: "", costAmount: null, appearsInStartShop: false, appearsInLaterPool: false, startsOnBoard: false, startBoardCount: null, baseProductionResource: "", baseProductionAmount: null, attack: null, health: null, specialAbility: "", description: "총기 공장의 생산물입니다. 모병소에서 보병을 만드는 재료로 쓰입니다." },
  { id: "shipyard", name: "조선소", type: "building", costResource: "gold", costResourceName: "황금", costAmount: 5, appearsInStartShop: true, appearsInLaterPool: false, startsOnBoard: false, startBoardCount: 0, baseProductionResource: "", baseProductionAmount: null, attack: null, health: null, specialAbility: "", description: "인구 2와 강철 3을 올리면 매 턴 군함을 생산합니다(레시피 r06)." },
  { id: "warship", name: "군함", type: "item", costResource: null, costResourceName: "", costAmount: null, appearsInStartShop: false, appearsInLaterPool: false, startsOnBoard: false, startBoardCount: null, baseProductionResource: "", baseProductionAmount: null, attack: null, health: null, specialAbility: "", description: "조선소의 생산물입니다. 모병소에서 초계함을 만드는 재료로 쓰입니다." },
  { id: "radio_address", name: "라디오 연설", type: "item", costResource: "gold", costResourceName: "황금", costAmount: 3, appearsInStartShop: true, appearsInLaterPool: false, startsOnBoard: false, startBoardCount: 0, baseProductionResource: "", baseProductionAmount: null, attack: null, health: null, specialAbility: "", description: "백악관 위에 올리면 턴 종료 시 사라지며 지지도 2를 생산하는 1회성 카드입니다(레시피 r02)." },
  { id: "recruitment_office", name: "모병소", type: "building", costResource: "gold", costResourceName: "황금", costAmount: 2, appearsInStartShop: true, appearsInLaterPool: true, startsOnBoard: false, startBoardCount: 0, baseProductionResource: "", baseProductionAmount: null, attack: null, health: null, specialAbility: "", description: "인구와 함께 총기·군함·군용차량 중 하나를 올리면 각각 보병·초계함·장갑차로 전환합니다(레시피 r07~r09). 시작 상점과 이후 풀에 모두 포함되어 등장 확률이 더 높습니다." },
  { id: "infantry", name: "보병", type: "army", costResource: null, costResourceName: "", costAmount: null, appearsInStartShop: false, appearsInLaterPool: false, startsOnBoard: false, startBoardCount: null, baseProductionResource: "", baseProductionAmount: null, attack: 2, health: 10, specialAbility: "", description: "모병소에서 인구 1 + 총기 1로 생산되는 기본 군대 카드입니다." },
  { id: "patrol_boat", name: "초계함", type: "army", costResource: null, costResourceName: "", costAmount: null, appearsInStartShop: false, appearsInLaterPool: false, startsOnBoard: false, startBoardCount: null, baseProductionResource: "", baseProductionAmount: null, attack: 5, health: 27, specialAbility: "전투에 참여 중일 때, 아군에 보병이 없으면 공격력이 1 증가한다.", description: "모병소에서 인구 2 + 군함 1로 생산됩니다. 전투 시스템은 아직 없어 특수 효과는 데이터로만 기록해뒀습니다." },
  { id: "gun_blueprint", name: "총기 설계도", type: "item", costResource: "gold", costResourceName: "황금", costAmount: 1, appearsInStartShop: false, appearsInLaterPool: true, startsOnBoard: false, startBoardCount: 0, baseProductionResource: "", baseProductionAmount: null, attack: null, health: null, specialAbility: "", description: "총기 공장 위에 올리면 턴 종료 시 사라지며 총기 1을 생산하는 1회성 카드입니다(레시피 r05)." },
  { id: "tank_factory", name: "전차 공장", type: "building", costResource: "gold", costResourceName: "황금", costAmount: 3, appearsInStartShop: false, appearsInLaterPool: true, startsOnBoard: false, startBoardCount: 0, baseProductionResource: "", baseProductionAmount: null, attack: null, health: null, specialAbility: "", description: "인구와 강철 2를 올리면 매 턴 군용차량을 생산합니다(레시피 r10)." },
  { id: "military_vehicle", name: "군용차량", type: "item", costResource: null, costResourceName: "", costAmount: null, appearsInStartShop: false, appearsInLaterPool: false, startsOnBoard: false, startBoardCount: null, baseProductionResource: "", baseProductionAmount: null, attack: null, health: null, specialAbility: "", description: "전차 공장의 생산물입니다. 모병소에서 장갑차의 재료로 쓰입니다. (이전에는 '전차'로 불렸으나 '군용차량'으로 통일)" },
  { id: "armored_car", name: "장갑차", type: "army", costResource: null, costResourceName: "", costAmount: null, appearsInStartShop: false, appearsInLaterPool: false, startsOnBoard: false, startBoardCount: null, baseProductionResource: "", baseProductionAmount: null, attack: null, health: null, specialAbility: "", description: "모병소에서 인구 1 + 군용차량 1로 생산됩니다. 공격력·체력은 직접 입력하실 예정이라 비워뒀습니다." },
];

var RECIPE_DATA = [
  { recipeId: "r01", ownerCardId: "white_house", ownerCardName: "백악관", timing: "턴종료", ingredients: [{ id: "support", qty: 3, consumed: true }], resultType: "modifyStat", resultCardId: "", resultQty: null, statTarget: "white_house.baseProductionAmount(gold)", statChange: 1, description: "지지도 3을 소모해 백악관의 황금 생산량을 영구히 1 증가시킵니다. 지지도를 다시 모으면 재발동됩니다. 능력치 변경 레시피라 아래 r02와는 경쟁하지 않고 같은 턴에 함께 발동될 수 있습니다.", sheetOrder: 0 },
  { recipeId: "r02", ownerCardId: "white_house", ownerCardName: "백악관", timing: "턴종료", ingredients: [{ id: "radio_address", qty: 1, consumed: true }], resultType: "produceCard", resultCardId: "support", resultQty: 2, statTarget: "", statChange: null, description: "라디오 연설을 소모해 지지도 2를 생산합니다 (1회성).", sheetOrder: 1 },
  { recipeId: "r03", ownerCardId: "gun_factory", ownerCardName: "총기 공장", timing: "턴종료", ingredients: [{ id: "population", qty: 1, consumed: false }], resultType: "produceCard", resultCardId: "guns", resultQty: 1, statTarget: "", statChange: null, description: "인구만 있으면 매 턴 총기 1을 생산합니다. 강철(r04)이나 총기 설계도(r05)까지 조건이 맞으면 생산량이 더 큰 그 레시피가 대신 적용됩니다.", sheetOrder: 2 },
  { recipeId: "r04", ownerCardId: "gun_factory", ownerCardName: "총기 공장", timing: "턴종료", ingredients: [{ id: "population", qty: 1, consumed: false }, { id: "steel", qty: 2, consumed: true }], resultType: "produceCard", resultCardId: "guns", resultQty: 2, statTarget: "", statChange: null, description: "인구와 강철을 함께 올리면 총기 2를 생산합니다. 이 공장의 레시피 중 생산량이 가장 커서, 조건이 겹치면 이 레시피가 우선 적용됩니다.", sheetOrder: 3 },
  { recipeId: "r05", ownerCardId: "gun_factory", ownerCardName: "총기 공장", timing: "턴종료", ingredients: [{ id: "gun_blueprint", qty: 1, consumed: true }], resultType: "produceCard", resultCardId: "guns", resultQty: 1, statTarget: "", statChange: null, description: "총기 설계도를 소모해 총기 1을 생산합니다(1회성). r04(생산량 2)와 조건이 겹치면 r04가 대신 적용됩니다.", sheetOrder: 4 },
  { recipeId: "r06", ownerCardId: "shipyard", ownerCardName: "조선소", timing: "턴종료", ingredients: [{ id: "population", qty: 2, consumed: false }, { id: "steel", qty: 3, consumed: true }], resultType: "produceCard", resultCardId: "warship", resultQty: 1, statTarget: "", statChange: null, description: "인구 2와 강철 3을 올리면 매 턴 군함을 생산합니다.", sheetOrder: 5 },
  { recipeId: "r07", ownerCardId: "recruitment_office", ownerCardName: "모병소", timing: "턴종료", ingredients: [{ id: "population", qty: 1, consumed: true }, { id: "guns", qty: 1, consumed: true }], resultType: "produceCard", resultCardId: "infantry", resultQty: 1, statTarget: "", statChange: null, description: "인구와 총기를 모두 소모해 보병을 생산합니다. 인구도 함께 소모되므로 매 턴 다시 채워야 합니다.", sheetOrder: 6 },
  { recipeId: "r08", ownerCardId: "recruitment_office", ownerCardName: "모병소", timing: "턴종료", ingredients: [{ id: "population", qty: 2, consumed: true }, { id: "warship", qty: 1, consumed: true }], resultType: "produceCard", resultCardId: "patrol_boat", resultQty: 1, statTarget: "", statChange: null, description: "인구 2와 군함을 모두 소모해 초계함을 생산합니다.", sheetOrder: 7 },
  { recipeId: "r09", ownerCardId: "recruitment_office", ownerCardName: "모병소", timing: "턴종료", ingredients: [{ id: "population", qty: 1, consumed: true }, { id: "military_vehicle", qty: 1, consumed: true }], resultType: "produceCard", resultCardId: "armored_car", resultQty: 1, statTarget: "", statChange: null, description: "인구와 군용차량을 모두 소모해 장갑차를 생산합니다.", sheetOrder: 8 },
  { recipeId: "r10", ownerCardId: "tank_factory", ownerCardName: "전차 공장", timing: "턴종료", ingredients: [{ id: "population", qty: 1, consumed: false }, { id: "steel", qty: 2, consumed: true }], resultType: "produceCard", resultCardId: "military_vehicle", resultQty: 1, statTarget: "", statChange: null, description: "인구와 강철 2를 올리면 매 턴 군용차량을 생산합니다.", sheetOrder: 9 },
];
